// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnggUa-__hWBAtl5JGYWtX3r3TwyVOYs4',
    appId: '1:148367614400:web:efff429d079c466f6d2825',
    messagingSenderId: '148367614400',
    projectId: 'esyincome-c0463',
    authDomain: 'esyincome-c0463.firebaseapp.com',
    storageBucket: 'esyincome-c0463.appspot.com',
    measurementId: 'G-R4FGSVP2E9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAv29uVwRar5Ux5nZI7O8YmbUtaTnl9nKo',
    appId: '1:148367614400:android:ade39da5ae59384f6d2825',
    messagingSenderId: '148367614400',
    projectId: 'esyincome-c0463',
    storageBucket: 'esyincome-c0463.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwO1y8mhlcG-UK5XV7ImoRL_qoQ4co8K0',
    appId: '1:148367614400:ios:a8b9c2c49756f44d6d2825',
    messagingSenderId: '148367614400',
    projectId: 'esyincome-c0463',
    storageBucket: 'esyincome-c0463.appspot.com',
    iosClientId: '148367614400-t493b0k4cqiu030o50qics1lcpiqu06m.apps.googleusercontent.com',
    iosBundleId: 'com.esy.earn',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBwO1y8mhlcG-UK5XV7ImoRL_qoQ4co8K0',
    appId: '1:148367614400:ios:a822ea5d55bdcb546d2825',
    messagingSenderId: '148367614400',
    projectId: 'esyincome-c0463',
    storageBucket: 'esyincome-c0463.appspot.com',
    iosClientId: '148367614400-r7ivtj8u9jud5ue7fh90l055prc5d8nr.apps.googleusercontent.com',
    iosBundleId: 'com.esy.earn.RunnerTests',
  );
}
